<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Jalium.UI.Gallery.Services</RootNamespace>
    <AssemblyName>Jalium.UI.Gallery.Services</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Jalium.UI\src\managed\Jalium.UI.Controls\Jalium.UI.Controls.csproj" />
    <ProjectReference Include="..\Jalium.UI.Gallery.Services.Interfaces\Jalium.UI.Gallery.Services.Interfaces.csproj" />
  </ItemGroup>

</Project>
