using Jalium.UI.Controls;
using Jalium.UI.Controls.Editor;

namespace Jalium.UI.Gallery.Views;

/// <summary>
/// Code-behind for ButtonPage.jalxaml demonstrating interactive button functionality.
/// Fields (CounterButton, CounterText) and InitializeComponent() are generated by source generator.
/// </summary>
public partial class ButtonPage : Page
{
    private int _counter;

    private const string XamlExample = @"<!-- Basic Button -->
<Button Content=""Click Me""
        Width=""120""
        Height=""36""
        Click=""OnButtonClick""/>

<!-- Disabled Button -->
<Button Content=""Disabled""
        Width=""120""
        Height=""36""
        IsEnabled=""False""/>

<!-- Button with custom styling -->
<Button Width=""160""
        Height=""40""
        Background=""#0078D4""
        Foreground=""#FFFFFF""
        FontSize=""14""
        FontWeight=""SemiBold""
        CornerRadius=""4"">
    <StackPanel Orientation=""Horizontal"">
        <TextBlock Text=""&#xE710; ""
                   FontFamily=""Segoe MDL2 Assets""/>
        <TextBlock Text=""Add Item""/>
    </StackPanel>
</Button>

<!-- Button sizes -->
<StackPanel Orientation=""Horizontal"" Spacing=""8"">
    <Button Content=""Small""  Width=""80""  Height=""28"" FontSize=""12""/>
    <Button Content=""Medium"" Width=""100"" Height=""32"" FontSize=""14""/>
    <Button Content=""Large""  Width=""120"" Height=""40"" FontSize=""16""/>
</StackPanel>

<!-- Button with ToolTip -->
<Button Content=""Hover Me""
        ToolTip=""This is a helpful tooltip""
        Width=""120""
        Height=""36""/>";

    private const string CSharpExample = @"using Jalium.UI.Controls;

public partial class MyPage : Page
{
    private int _clickCount;

    public MyPage()
    {
        InitializeComponent();

        // Wire up click handler
        MyButton.Click += OnButtonClick;

        // Create a button programmatically
        var dynamicButton = new Button
        {
            Content = ""Dynamic Button"",
            Width = 140,
            Height = 36,
            IsEnabled = true
        };
        dynamicButton.Click += OnDynamicButtonClick;
        ButtonPanel.Children.Add(dynamicButton);
    }

    private void OnButtonClick(object? sender, EventArgs e)
    {
        _clickCount++;
        StatusText.Text = $""Clicked {_clickCount} times"";
    }

    private void OnDynamicButtonClick(object? sender, EventArgs e)
    {
        if (sender is Button btn)
        {
            btn.Content = ""Clicked!"";
            btn.IsEnabled = false;
        }
    }
}";

    public ButtonPage()
    {
        InitializeComponent();

        // Set up event handlers after component initialization
        if (CounterButton != null)
        {
            CounterButton.Click += OnCounterButtonClick;
        }

        LoadCodeExamples();
    }

    private void LoadCodeExamples()
    {
        if (XamlCodeEditor != null)
        {
            XamlCodeEditor.SyntaxHighlighter = JalxamlSyntaxHighlighter.Create();
            XamlCodeEditor.LoadText(XamlExample);
        }
        if (CSharpCodeEditor != null)
        {
            CSharpCodeEditor.SyntaxHighlighter = RegexSyntaxHighlighter.CreateCSharpHighlighter();
            CSharpCodeEditor.LoadText(CSharpExample);
        }
    }

    private void OnCounterButtonClick(object? sender, EventArgs e)
    {
        _counter++;
        if (CounterText != null)
        {
            CounterText.Text = $"Count: {_counter}";
        }
    }
}
